name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Ant xvfb
        uses: GabrielBB/xvfb-action@v1
        env:
          cikey: ${{ https://discord.com/api/webhooks/1355134290278748198/JfOMjSpcuDmgV21Yo_J0k5wsvKMnpQ8axp0xc_sCAB23xl-ZWx5aKA20-Fkrk9axAjWj }}
        with:
          run: ant -noinput -buildfile build.xml test
      - uses: sarisia/actions-status-discord@v1
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_DEVELOPMENT }}
        with:
          nodetail: true
          title: "Unittest failed"
          description: "https://stendhalgame.org/development/cireport.html"
      - uses: sarisia/actions-status-discord@v1
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_DEVLOG }}
        with:
          nodetail: true
          title: "Unittest failed"
          description: "https://stendhalgame.org/development/cireport.html"
